import First from '@/components/first'
import React from 'react'
import Head from 'next/head'
import styles from '@/styles/about.module.css'
import Image from 'next/image';
import logo from "../public/static/logo.png"

const about = () => {
  return (
    <>
    <Head>
        <title>NORC. Construction</title>
        {/* <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <First/>
      <main className={styles.main}>
        <div className={styles.description}>
      <Image   src={logo}  width={200} alt="Logo" />
        <h4 className={styles.p} >Construction Firm</h4>
        <h1 className={styles.h1}>About Norc</h1>
        </div>
        <div>
        hello
      </div>
      </main>
      
    </>
  )
}

export default about