import React from 'react';
import Head from 'next/head';
import Image from 'next/image';
import logo from "@/public/static/logo.png";
import First from '@/components/First';
import styles from '../styles/BlogPost.module.css';
import blog01 from "../public/static/blog01.jpg";
import blog02 from "../public/static/blog2.jpg";
import author from "../public/static/ServicesCard3.jpg";
import Button from 'react-bootstrap/Button';
import Form from 'react-bootstrap/Form';
import ContactUs from '../components/ContactUs'

const Blog01 = () => {
  return (<>
    <Head>
      <title>NORC. Construction</title>
      {/* <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" /> */}
    </Head>
    <First />
    <main className={styles.main}>
      <div className={styles.description}>
        <Image className={styles.image} src={logo} alt="Logo" />
        <p className={styles.p}>Our Blog</p>
        < hr className={styles.hrcolor} />

        <h1 className={styles.h1}>Construction Delivery <br/><span style={{ color: 'black' }}>Methods Training</span></h1>
        <div className={styles.row}>
          <div className={styles.column} style={{ width: "80%" }}>
            <Image src={blog01} alt="Blog" className={styles.img} />
            <h5 className={styles.h5}>Construction Delivery Methods Training</h5>
            <p style={{ color: "white" }}>Construction elibero tristique mattis suspen dissen potenti seden
              laoreen ultricies magna, in dignissim justo porta eget miss vention luctus magna numsation
              the pelentesue luctus maga numsaton vivention esellentesue the tenis vitae mollie.</p>
              <p style={{ color: "white" }}>Quisque pretium fermentum quam, sit amet cursus ante sollicitudin vel. 
              Morbi consequat risus consequat, porttitor orci sit amet, iaculis nisl. Integer quis sapien nec elit ultrices 
              euismod sit amet id lacus. Sed a imperdiet erat. Duis eu est dignissim lacus dictum hendrerit quis vitae mi. 
              Fusce eu nulla ac nisi cursus tincidunt. Interdum et malesuada fames ac ante ipsum primis in faucibus.</p>
              <p style={{ color: "white" }}>Construction elibero tristique mattis suspen dissen potenti seden
              laoreen ultricies magna, in dignissim justo porta eget miss vention luctus magna numsation
              the pelentesue luctus maga numsaton vivention esellentesue the tenis vitae mollie.</p>

              <Image src={blog01} alt="Blog" width={400} />
              <Image src={blog02} alt="Blog" width={400}  />
 <p style={{ color: "white" }}>Construction elibero tristique mattis suspen dissen potenti seden
              laoreen ultricies magna, in dignissim justo porta eget miss vention luctus magna numsation
              the pelentesue luctus maga numsaton vivention esellentesue the tenis vitae mollie.
               Construction elibero tristique mattis suspen dissen potenti seden
              laoreen ultricies magna, in dignissim justo porta eget miss vention luctus magna numsation
              the pelentesue luctus maga numsaton vivention esellentesue the tenis vitae mollie.</p>
              
            
          </div>
          <div className={styles.column} style={{width:"20%"}}>
          <div className={styles.card}>
              <h4>Recent Posts</h4>
              <Image src={blog01} width={100} alt="Logo" />
              <p className={styles.recentpost}>Construction Delivery</p>
              <p>   Methods Training</p>
              <Image src={blog01} width={100} alt="Logo" />
              <p className={styles.recentpost}>Construction Delivery</p>
              <p>   Methods Training</p>
              <Image src={blog01} width={100} alt="Logo" />
              <p className={styles.recentpost}>Construction Delivery</p>
              <p>   Methods Training</p>

            </div>
            <div className={styles.card}>
              <h4>Archieve</h4>
              < hr style={{ color: 'black' }} />



              <p className={styles.recentpost}>2023 December</p>
              <br />

              <p className={styles.recentpost}>2023 January</p>
              <br />

              <p className={styles.recentpost}>2023 Febrauary </p>
              <br />

            </div>
          </div>
          
          
          
          
        </div>
        
        <div  className={styles.post} style={{ width: "80%" }}>
          <h5 >Betty Misse  </h5>
          <p className={styles.postp}>29 Dec 2022</p>
          <br/>
          
        </div>
        <Image src={author} alt="Author"  className={styles.postimg}/>
        <p className={styles.postp} style={{color:"white"}}>Nulla miss ultricies nibh non dolor maximus sceleue inte molliser
           faubs neque nectar tincidunte aliquam erat volutpat sraeser tempore. </p>
           <h5 style={{color:"orange"}}>Leave a Reply</h5>
           <Form>
      <Form.Group className="mb-3" controlId="formBasicEmail">
        <Form.Control type="text" placeholder="Name*" /> 
        <Form.Control type="text" placeholder="Surname*" className='mt-2' />
        <Form.Control type="email" placeholder="Enter Your Email*"  className='mt-2'/>
        <p className='mt-2'>Leave Your Comment</p>
        <Form.Control type="text" placeholder=""  className='mt-2' style={{fontSize:"50px"}}/> 
        
      </Form.Group>
      <Button variant="warning" type="submit">
        Submit
      </Button>
    </Form>
        < hr className={styles.hrcolor} />
        
      </div>
      <ContactUs/>
    </main>
  </>
  )
}

export default Blog01