import React from 'react';
import Head from 'next/head';
import Image from 'next/image';
import logo from "@/public/static/logo.png";
import First from '@/components/First';
import styles from '../styles/Blog01.module.css';

const Blog01 = () => {
  return (<>
    <Head>
      <title>NORC. Construction</title>
      {/* <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" /> */}
    </Head>
    <First />
    <main className={styles.main}>
      <div className={styles.description}>
        <Image className={styles.image} src={logo} alt="Logo" />
        < hr className={styles.hrcolor} />
      </div>

    </main>
  </>
  )
}

export default Blog01