import React from 'react';
import Head from 'next/head';
import First from '@/components/First';
import logo from "../public/static/logo.png"
import styles from "@/styles/Contact.module.css"
import Image from 'next/image';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faPhone } from '@fortawesome/free-solid-svg-icons';
import { faFax } from '@fortawesome/free-solid-svg-icons';
import { faEnvelope } from '@fortawesome/free-solid-svg-icons';
import { faLocation } from '@fortawesome/free-solid-svg-icons';
import { Button } from 'react-bootstrap';




const contact = () => {
  return (<>
    <Head>
      <title>NORC. Construction</title>
      {/* <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" /> */}
    </Head>
    <First />
    <main className={styles.main}>
      <div className={styles.description}>
        <Image className={styles.image} src={logo} alt="Logo" />
        <h6 className={styles.h6}>Get in Touch</h6>
        <h1 className={styles.h1}>Contact  <span className={styles.span}>Us</span></h1>
        < hr className={styles.hrcolor} />

        <div className={styles.row}>
          <div className={styles.column}>
            <h4>Contact Information</h4>
            <p>Contact nullam usamcoen the drana duru metus utah osare asya
              mavna busnini viventa the ornare ipsum.
              Curabitur luctus mana numsation pellentesque the miss tenis mollie.</p>
            <div className={styles.fontrow}>
              <h5 > <FontAwesomeIcon icon={faPhone} className={styles.font} />Call Us</h5>
              <p className='mt-3' >+977625659626</p>
            </div>
            <div className={styles.fontrow}>
              <h5 > <FontAwesomeIcon icon={faFax} className={styles.font} />Fax Number</h5>
              <p className='mt-3' >+977515625659626</p>
            </div>
            <div className={styles.fontrow}>
              <h5 > <FontAwesomeIcon icon={faEnvelope} className={styles.font} />Send us an email</h5>
              <p className='mt-3' >info@demo.test.com</p>
            </div>
            <div className={styles.fontrow}>
              <h5 > <FontAwesomeIcon icon={faLocation} className={styles.font} />Visit our office</h5>
              <p className='mt-3' > Charleston, 29401 USA</p>
            </div>

          </div>
          <div className={styles.column}>
            <div className={styles.card}>
              <h5>Get in Touch</h5>
             
             <form className={styles.form}>
                  <input type="text" name="name" placeholder='Your Name*' className={styles.input}/>
                  <input type="email" name="name" placeholder='Your Email*'  className={styles.input}/>
                  <input type="text" name="name" placeholder='Your Subject*' className={styles.input}/>
                  <textarea placeholder='Message*'className={styles.input}>
                    
                  </textarea>
                 
              </form>
              <Button variant="warning" className='mx-5 mb-2' >Send Message</Button>

            </div>
          </div>
          

        </div>
       <div className={styles.row}>
       <div className={styles.map} >
        <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d441.7009247609158!2d85.32088500000002!3d27.667616!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x92f2c1f2e7deb5c7!2sCloud%20Nepalaya%20Pvt%20Ltd!5e0!3m2!1sen!2sus!4v1677399147040!5m2!1sen!2sus" width="600" height="450"  allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
               </div>
               <div>
                <h1 className={styles.office}>Office Location</h1>
               </div>

       </div>

      </div>


    </main>
  </>

  )
}

export default contact