import React from 'react'
import ServicesCard from '@/components/ServicesCard';
import Head from 'next/head';
import First from '@/components/First';
import styles from '@/styles/Services.module.css';
import Image from 'next/image';
import logo from "../public/static/logo.png"

const services = () => {
  return (
    <>
    <Head>
        <title>NORC. Construction</title>
        {/* <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <First/>
      <main className={styles.main}>
      <div className={styles.description}>
      <Image  className={styles.image} src={logo} alt="Logo"  />
        
          <h6 className={styles.h6}>What We Do</h6>
          <h1 className={styles.h1}>Our  <span className={styles.span}>Services</span></h1>
          < hr className={styles.hrcolor}/>
          
          </div>

       

      </main>
      

   
    </>
  )
}

export default services